#!/usr/bin/env python3
"""Write apps-script/coordinator-transport-data.gs from master_bus_table.csv (run build_master.py first).
That file is the fleet roster + document-expiry baseline the Coordinator backend merges live form uploads onto.
Re-run after fleet changes, then paste the regenerated file into the Coordinator Apps Script project.
"""
import csv, json
from pathlib import Path

HERE = Path(__file__).parent
DOCS = ["insurance", "fitness", "mv_tax", "pollution", "route_permit", "speed_governor"]
fleet = [{"reg": r["reg_no"], "bus": r["bus_no"], "campus": r["campus"], "operational": r["operational"] == "yes",
          "route": r["route"], "driver": r["driver"].strip(),
          "docs": {d: [r[f"{d}_valid_to"], r[f"{d}_src"]] for d in DOCS if r[f"{d}_valid_to"]}}
         for r in csv.DictReader(open(HERE / "master_bus_table.csv"))]
out = HERE.parent / "apps-script" / "coordinator-transport-data.gs"
out.write_text("// GENERATED by transport/export_to_coordinator.py -- do not edit by hand.\n"
               "// Fleet roster and document-expiry baseline (newest of the submission form and the Drive index at generation time).\n"
               "// Source: V3 Transport Management System 2026 workbook + drive-index/records.db + Transport Document Submission form.\n"
               "const COORD_TRANSPORT_FLEET = " + "[\n" + ",\n".join(" " + json.dumps(v) for v in fleet) + "\n];\n")
print(len(fleet), "vehicles ->", out)
